config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :lists, only: [:show, :index, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end

  end


  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
   <%= f.association :movie %>
  <%= f.submit "Add Bookmark", class: "btn btn-success" %>
<% end %>

<%= link_to "Back", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Movie list</h1>
<br>

<ul>
  <% @lists.each do |l| %>
    <li><%= l.name %></li>
    <%= link_to "See details", list_path(l) %>
  <% end %>
</ul>

<%= link_to "create a new movie list", new_list_path, class: "btn btn-success"%>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
 <%# <p>newhtml</p> %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>
<br>
<%= link_to "Back", lists_path %>

app/views/lists/show.html.erb
<div>
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<h1><%= @list.name %></h1>
</div>
<br>

<% @bookmarks.each do |bookmark| %>


<% movie = bookmark.movie %>
<div class="card">
  <h1><%= movie.title %></h1>
  <br>
  <p>overview: <%= movie.overview %></p>
  <p>rating: <%= movie.rating %></p>
  <img src=<% "#{movie.poster_url}" %> alt=<%= "#{movie.title}" %>>
  <p><%= @bookmark.comment %></p>
</div>
<% end %>


<%= link_to "Add movie", new_list_bookmark_path(@list.id), class: "btn btn-success" %>